# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='NotLoginUser', max_length=255)),
                ('time', models.DateTimeField(auto_now=True)),
                ('blog_name', models.CharField(default='', max_length=255)),
                ('did_like', models.BooleanField(default=False)),
                ('user_comment_count', models.IntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
