# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-02 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinginfo',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
