# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 03:41
from __future__ import unicode_literals

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('publish_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('C', 'C'), ('UNIX', 'UNIX'), ('Python', 'Python'), ('MachineLearning', 'MachineLearning'), ('Django', 'Django'), ('Math', 'Math'), ('Network', 'Network'), ('OpenGL', 'OpenGL'), ('Unity', 'Unity'), ('PostgreSQL', 'PostgreSQL'), ('STM32', 'STM32'), ('Bootstrap', 'Bootstrap'), ('Vim', 'Vim'), ('Mac', 'Mac'), ('Cooking', 'Cooking'), ('ReadingNote', 'ReadingNote'), ('Music', 'Music'), ('English', 'English'), ('Japanese', 'Japanese'), ('French', 'French')], default='Python', max_length=255)),
                ('cover_image', models.ImageField(blank=True, upload_to=Blog.models.upload_file_name)),
                ('cover_breif', models.TextField(blank=True, max_length=1500)),
                ('draft', models.BooleanField(default=True)),
                ('is_series', models.BooleanField(default=False)),
                ('series_keyword', models.CharField(blank=True, max_length=100)),
                ('series_index', models.IntegerField(blank=True)),
            ],
        ),
    ]
