# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_date', models.DateField(auto_now=True)),
                ('publish_date', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('C', 'C'), ('UNIX', 'UNIX'), ('Python', 'Python'), ('MachineLearning', 'MachineLearning'), ('Django', 'Django'), ('Math', 'Math'), ('Network', 'Network'), ('OpenGL', 'OpenGL'), ('Unity', 'Unity'), ('PostgreSQL', 'PostgreSQL'), ('STM32', 'STM32'), ('Bootstrap', 'Bootstrap'), ('Vim', 'Vim'), ('Mac', 'Mac'), ('Cooking', 'Cooking'), ('ReadingNote', 'ReadingNote'), ('Music', 'Music'), ('English', 'English'), ('Japanese', 'Japanese'), ('French', 'French')], default='Python', max_length=255)),
                ('cover_image_url', models.URLField(null=True)),
                ('cover_breif', models.TextField(blank=True, max_length=1500)),
                ('draft', models.BooleanField(default=True)),
                ('is_series', models.BooleanField(default=False)),
                ('series_keyword', models.CharField(blank=True, max_length=100)),
                ('series_index', models.IntegerField(null=True)),
                ('test', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
