# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='test1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
