# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-26 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='series_index',
            field=models.IntegerField(null=True),
        ),
    ]
