# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('C', 'C'), ('UNIX', 'UNIX'), ('Python', 'Python'), ('MachineLearning', 'MachineLearning'), ('Django', 'Django'), ('Math', 'Math'), ('Network', 'Network'), ('OpenGL', 'OpenGL'), ('Unity', 'Unity'), ('PostgreSQL', 'PostgreSQL'), ('STM32', 'STM32'), ('Bootstrap', 'Bootstrap'), ('Vim', 'Vim'), ('Mac', 'Mac'), ('Cooking', 'Cooking'), ('ReadingNote', 'ReadingNote'), ('Music', 'Music'), ('English', 'English'), ('Japanese', 'Japanese'), ('French', 'French'), ('Writing', 'Writing')], default='Python', max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
