# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-30 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_blog_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='test',
        ),
    ]
