# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='like',
            table='Like',
        ),
    ]
